### ISSUE TITLE
Is there a way to delete a link between tasks?

### ISSUE THREAD

**Issue by ricardodemauro** [zehntech/zt-gantt#11]
Hi, 

thanks for the hard work on this library. I was just thinking about a way to delete a link between tasks.

How the user should do to achieve that?

Thanks,

**Comment by ZTSS221** [comment]
Hi there,

I'm glad to hear you're finding the library helpful! 

To delete a link between tasks, you can use the `deleteLink(id)` method where **id** is the id of the link you want to remove.

Additionally, it's great to know that you have the onLinkDblClick event for added convenience, making it easier for users to interact with and manage task links. This event likely allows users to double-click on a link to trigger specific actions or prompts related to that link.

For more detailed information on how to use these features and get the most out of the library, please refer to the [documentation](https://github.com/zehntech/zt-gantt/blob/main/public/Documentaion/Gantt-Chart-Documentation.pdf).

If you have any more questions or need further assistance with the library or any related tasks, please feel free to ask. We're here to help!

Best regards,
Sunil Solanki

**Comment by ricardodemauro** [comment]
Thanks for the directions Sunil!
