### ISSUE TITLE
[Question] Is there any way to do Dispose on chart?

### ISSUE THREAD

**Issue by joao2391** [zehntech/zt-gantt#2]
Hi!

Is it possible to dispose or destroy the chart?

Thanks!

**Comment by ZTSS221** [comment]
Hello @joao2391,

Yes, it is possible to dispose or destroy the chart. When you say "dispose" or "destroy," it usually means removing the chart instance from the DOM and freeing up any associated resources to prevent memory leaks.

To destroy the chart you can use the below method 
gantt.destroy();

Please update the latest version of the library.
